name: 'Dev Data Landing Zone'
 
on:
  push:
    branches: [ main ]
    paths:
    - 'landingzone-dev/**'
    - ".github/workflows/terraform_dlz.yaml"
  pull_request:
    paths:
    - 'landingzone-dev/**'
    - ".github/workflows/terraform_dlz.yaml"

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'DEV_DLZ_Deployment'
    runs-on: ubuntu-latest
    environment: 
      name: dev

## Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        working-directory: ./landingzone-dev
        shell: bash
    steps:
# Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

# Login to Azure 
    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        enable-AzPSSession: true

# # Login
#     - name: Login to Azure
#       uses: azure/CLI@v1
#       with:
#         azcliversion: latest
#         inlineScript: |
#           az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

# Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with: 
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
# https://github.com/actions/setup-node 
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
# Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
        #az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
# Formatting of tf files
    - name: Terraform Fmt
      run: terraform fmt      
# # Generates an execution plan for Terraform
    - name: Terraform Plan
      if: github.event_name == 'pull_request'
      run: terraform plan -no-color
# On push to main, build or change infrastructure according to Terraform configuration files
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve